---
# tasks file for roles/elb
- name: Get facts from ec2 instances
  ec2_remote_facts:
    profile: "{{ aws.profile }}"
    region: "{{ aws.region }}"
    filters:
      "tag:Environment": Demo
      "tag:Name": web app
  register: ec2_facts

- name: Manage instances on ELB
  ec2_elb:
    profile: "{{ aws.profile }}"
    instance_id: "{{ item.id }}"
    ec2_elbs: ELB-8080
    state: present
    region: "{{ aws.region }}"
  with_items: "{{ ec2_facts.instances }}"
