- name: Create key pair
  ec2_key:
    profile: "{{ aws.profile }}"
    name: Demo
    region: "{{ aws.region }}"
    key_material: "{{ aws.ssh_public_key_file }}"

- name: Create instances
  ec2:
    profile: "{{ aws.profile }}"
    assign_public_ip: yes
    region: "{{ vpc.region }}"
    group: "EC2 restricted sg"
    instance_type: c4.large
    image: ami-2051294a
    vpc_subnet_id: "{{ item.id }}"
    monitoring: yes
    wait: yes
    instance_tags:
      Environment: Demo
      Name: "web app"
    count_tag: "web app"
    exact_count: 1
  with_items: "{{ vpc_out.subnets }}"
  register: ec2_out  
