- name: Create key pair
  ec2_key:
    profile: "{{ aws.profile }}"
    name: Demo
    region: "{{ aws.region }}"
    key_material: "{{ aws.ssh_public_key_file }}"

- name: Create instances (c4.large)
  ec2:
    profile: "{{ aws.profile }}"
    assign_public_ip: yes
    region: "{{ aws.region }}"
    group: EC2 restricted sg
    instance_type: t2.micro
    image: ami-775e4f16
    key_name: Demo
    vpc_subnet_id: "{{ item.id }}"
    #vpc_subnet_id: subnet-729ba416
    monitoring: yes
    wait: yes
    instance_tags:
      Environment: Demo
      Name: web app
  with_items: "{{ vpc_out.subnets }}"
  register: ec2_out

- name: Refresh inventory
  meta: refresh_inventory
