- name: Get subnets ids
  set_fact:
    subnets_ids: "{{ vpc_out.subnets | map(attribute='id') | list }}"

- name: Create ELB
  ec2_elb_lb:
    profile: "{{ aws.profile }}"
    name: ELB-8080
    state: present
    region: "{{ aws.region }}"
    subnets: "{{ subnets_ids }}"
    security_group_names:
      - "ELB pub 8080"
    cross_az_load_balancing: yes
    listeners:
      - protocol: http
        load_balancer_port: 8080
        instance_protocol: http
        instance_port: 8080
    health_check:
      ping_protocol: http
      ping_port: 8080
      ping_path: "/"
      response_timeout: 5
      interval: 30
      unhealthy_threshold: 10
      healthy_threshold: 10
