- name: ELB security group
  ec2_group:
    name: "ELB pub 8080"
    vpc_id: "{{ vpc_out.get_id_from_this_var | vpc_facts.get_id_from_this_var }}"
    region: "{{ aws.region }}"
    profile: "{{ aws.profile }}"
    rules:
      - proto: tcp
        from_port: 8080
        to_port: 8080
        cidr_ip: 0.0.0.0/0
    rules_egress:
      - proto: all
        cidr_ip: 0.0.0.0/0

- name: EC2 security group
  ec2_group:
    name: "EC2 restricted sg"
    vpc_id: "{{ vpc_out.get_id_from_this_var | vpc_facts.get_id_from_this_var }}"
    region: "{{ aws.region }}"
    profile: "{{ aws.profile }}"
    rules:
      - proto: all
        cidr_ip: 10.0.0.0/8
    rules_egress:
      - proto: all
        cidr_ip: 0.0.0.0/0
