- name: Ensure Dockerfile is present
  copy:
    src="Dockerfile"
    dest="/tmp/Dockerfile"

- name: Ensure spring boot jar is present
  copy:
    src="gs-spring-boot-docker-0.1.0.jar"
    dest="/tmp/gs-spring-boot-docker-0.1.0.jar"

- name: Build Docker Image
  shell: "docker build -f /tmp/Dockerfile -t demo ."

- name: Run container (detached)
  shell: "docker run -p 8080:8080 -t demo -d"
