# configure path to testit

- name: Ensure Dockerfile is present
  copy:
    src="Dockerfile"
    dest="{{ docker.path }}/Dockerfile"
    owner="{{ docker.user }}"

- name: Ensure spring boot jar is present
  copy:
    src="gs-spring-boot-docker-0.1.0.jar"
    dest="{{ docker.path }}/gs-spring-boot-docker-0.1.0.jar"
    owner="{{ docker.user }}"

- name: Build Docker Image
  docker_image:
    name: demo
    state: build
    path: "{{ docker.path }}"

- name: Run container (detached)
  docker_container:
    name: Demo
    image: demo
    state: started
    published_ports: 8080:8080
